<a href="https://colab.research.google.com/github/rahulbhoyar1995/web-scraping-projects/blob/main/project_2_scraping_website_tables_using_pandas/4_nba_2020_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Author: Rahul Bhoyar

In this mini-project, we will scrape the NBA 2020 players data.

URL to be scraped : https://www.basketball-reference.com/leagues/NBA_2020_totals.html

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
URL = 'https://www.basketball-reference.com/leagues/NBA_2020_totals.html'
req = requests.get(URL)

In [2]:
soup = BeautifulSoup(req.content, 'html.parser')

In [4]:
tables = soup.find(name='table')

In [5]:
print("The total number of tables are :", len(tables))

The total number of tables are : 8

In [6]:
tables = pd.read_html(str(tables))
print("Total number of tables are :", len(tables))

Total number of tables are : 1

Let's create a Pandas Dataframe from the table.

In [8]:
nba_data_df = tables[0].set_index('Rk')
print("NBA Players Data (2020) :")
print("-"*200)
nba_data_df

NBA Players Data (2020) :
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
Rk,,,,,,,,,,,,,,,,,,,,,
1,Steven Adams,C,26,OKC,63,63,1680,283,478,.592,...,.582,207,376,583,146,51,67,94,122,684
2,Bam Adebayo,PF,22,MIA,72,72,2417,440,790,.557,...,.691,176,559,735,368,82,93,204,182,1146
3,LaMarcus Aldridge,C,34,SAS,53,53,1754,391,793,.493,...,.827,103,289,392,129,36,87,74,128,1001
4,Kyle Alexander,C,23,MIA,2,0,13,1,2,.500,...,NaN,2,1,3,0,0,0,1,1,2
5,Nickeil Alexander-Walker,SG,21,NOP,47,1,591,98,266,.368,...,.676,9,75,84,89,17,8,54,57,267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,Trae Young,PG,21,ATL,60,60,2120,546,1249,.437,...,.860,32,223,255,560,65,8,289,104,1778
526,Cody Zeller,C,27,CHO,58,39,1341,251,479,.524,...,.682,160,251,411,88,40,25,75,140,642
527,Tyler Zeller,C,30,SAS,2,0,4,1,4,.250,...,NaN,3,1,4,0,0,0,0,0,2
528,Ante Žižić,C,23,CLE,22,0,221,41,72,.569,...,.737,18,48,66,6,7,5,10,27,96
529,Ivica Zubac,C,22,LAC,72,70,1326,236,385,.613,...,.747,197,346,543,82,16,66,61,168,596

In this mini-project, we have successfully scraped the NBA 2020 data and store it in Pandas Dataframe.